#!/usr/bin/env bash
# Script to run some basic git commands

git pull
pull=$?
if [[ "$pull" -ne 0 ]]
then
        echo "Fix git pull error and run script again"
        exit
fi

git add .

# Prompt for commit message
echo "Please enter your commit message: "
read -r message

git commit -m "$message"
git push origin HEAD
