#!/usr/bin/env bash
# Script to run basic Git commands in bash

git_cmd() {
    git "$@"
    local exit_code=$?
    if [[ "$exit_code" -ne 0 ]]; then
        echo "Fix the Git command error and run the script again."
        exit "$exit_code"
    fi
}

git_cmd pull
git_cmd add .
read -p "Please enter your commit message: " message
git_cmd commit -m "$message"
git_cmd push origin HEAD
